
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemm' kernels.
//
// =================================================================================================

#include "database/kernels/myxgemm/myxgemm.hpp"
#include "database/kernels/myxgemm/myxgemm_16.hpp"
#include "database/kernels/myxgemm/myxgemm_32.hpp"
#include "database/kernels/myxgemm/myxgemm_3232.hpp"
#include "database/kernels/myxgemm/myxgemm_64.hpp"
#include "database/kernels/myxgemm/myxgemm_6464.hpp"
