
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Myxgemm' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry MyXgemmHalf;
extern const DatabaseEntry MyXgemmSingle;
extern const DatabaseEntry MyXgemmComplexSingle;
extern const DatabaseEntry MyXgemmDouble;
extern const DatabaseEntry MyXgemmComplexDouble;

} // namespace database
} // namespace clblast
